--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ATTACH_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_ATTACH_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BNO
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_BNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_DATA
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_BOARD_DATA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_FREE
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_BOARD_FREE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_BOARD_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_QNA
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_BOARD_QNA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMENT_CNUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_COMMENT_CNUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FILE_BNO
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_FILE_BNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FREE_BNO
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_FREE_BNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QNA_BNO
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_QNA_BNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REPLY_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_REPLY_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD_DATA
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."BOARD_DATA" 
   (	"NUM" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"VISITCOUNT" NUMBER DEFAULT 0, 
	"BOARDTYPE" VARCHAR2(10 BYTE) DEFAULT 'data', 
	"NAME" VARCHAR2(30 BYTE), 
	"LIKECOUNT" NUMBER DEFAULT 0, 
	"FILENAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_FREE
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."BOARD_FREE" 
   (	"NUM" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"VISITCOUNT" NUMBER DEFAULT 0, 
	"BOARDTYPE" VARCHAR2(10 BYTE) DEFAULT 'free', 
	"NAME" VARCHAR2(30 BYTE), 
	"LIKECOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_QNA
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."BOARD_QNA" 
   (	"NUM" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"VISITCOUNT" NUMBER DEFAULT 0, 
	"BOARDTYPE" VARCHAR2(10 BYTE) DEFAULT 'qna', 
	"NAME" VARCHAR2(30 BYTE), 
	"LIKECOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."MEMBER" 
   (	"ID" VARCHAR2(50 BYTE), 
	"PASS" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"REGIDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into WEBPROJECT_DB.BOARD_DATA
SET DEFINE OFF;
Insert into WEBPROJECT_DB.BOARD_DATA (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT,BOARDTYPE,NAME,LIKECOUNT,FILENAME) values (1,'124','12424','12345',to_date('25/12/12','RR/MM/DD'),0,'data','1234',0,'124');
REM INSERTING into WEBPROJECT_DB.BOARD_FREE
SET DEFINE OFF;
Insert into WEBPROJECT_DB.BOARD_FREE (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT,BOARDTYPE,NAME,LIKECOUNT) values (7,'1111','1111','1111',to_date('25/12/12','RR/MM/DD'),2,'free','1111',0);
Insert into WEBPROJECT_DB.BOARD_FREE (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT,BOARDTYPE,NAME,LIKECOUNT) values (9,'12342134','12345213542135','12345',to_date('25/12/12','RR/MM/DD'),2,'free','1234',0);
Insert into WEBPROJECT_DB.BOARD_FREE (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT,BOARDTYPE,NAME,LIKECOUNT) values (1,'뿡엥','1234','user01',to_date('25/12/11','RR/MM/DD'),4,'free','테스트유저',0);
Insert into WEBPROJECT_DB.BOARD_FREE (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT,BOARDTYPE,NAME,LIKECOUNT) values (2,'1111','1111','1111',to_date('25/12/11','RR/MM/DD'),14,'free','1111',0);
Insert into WEBPROJECT_DB.BOARD_FREE (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT,BOARDTYPE,NAME,LIKECOUNT) values (3,'124124','12412412','1111',to_date('25/12/11','RR/MM/DD'),6,'free','1111',0);
Insert into WEBPROJECT_DB.BOARD_FREE (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT,BOARDTYPE,NAME,LIKECOUNT) values (5,'2222','222222','2222',to_date('25/12/11','RR/MM/DD'),1,'free','2222',0);
Insert into WEBPROJECT_DB.BOARD_FREE (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT,BOARDTYPE,NAME,LIKECOUNT) values (6,'222222','22222222222','2222',to_date('25/12/11','RR/MM/DD'),3,'free','2222',0);
REM INSERTING into WEBPROJECT_DB.BOARD_QNA
SET DEFINE OFF;
REM INSERTING into WEBPROJECT_DB.MEMBER
SET DEFINE OFF;
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,EMAIL,PHONE,REGIDATE) values ('1234','1234','1234',null,null,to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,EMAIL,PHONE,REGIDATE) values ('12341','1234','1234','12344@naver.com','123-4123-4123',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,EMAIL,PHONE,REGIDATE) values ('12345','1234','1234','12344@naver.com','111-1111-1111',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,EMAIL,PHONE,REGIDATE) values ('musthave','1234','일반사용자','musthave@a.com','010-1111-2222',to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,EMAIL,PHONE,REGIDATE) values ('admin','1234','관리자','admin@a.com','010-3333-4444',to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,EMAIL,PHONE,REGIDATE) values ('user01','1234','테스트유저','user01@example.com','010-2345-6789',to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,EMAIL,PHONE,REGIDATE) values ('1111','1111','1111',null,null,to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,EMAIL,PHONE,REGIDATE) values ('11111','11111','11111','1111@naver.com','111-1111-1111',to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,EMAIL,PHONE,REGIDATE) values ('2222','2222','2222','22222@naevr.com','222-2222-2222',to_date('25/12/11','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008576
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008576" ON "WEBPROJECT_DB"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008586
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008586" ON "WEBPROJECT_DB"."BOARD_FREE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008597
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008597" ON "WEBPROJECT_DB"."BOARD_QNA" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008608
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008608" ON "WEBPROJECT_DB"."BOARD_DATA" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008608
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008608" ON "WEBPROJECT_DB"."BOARD_DATA" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008586
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008586" ON "WEBPROJECT_DB"."BOARD_FREE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008597
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008597" ON "WEBPROJECT_DB"."BOARD_QNA" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008576
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008576" ON "WEBPROJECT_DB"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD_DATA
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" MODIFY ("BOARDTYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" MODIFY ("LIKECOUNT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_FREE
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" MODIFY ("BOARDTYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" MODIFY ("LIKECOUNT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_QNA
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" MODIFY ("BOARDTYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" MODIFY ("LIKECOUNT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_DATA
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD_DATA" ADD FOREIGN KEY ("ID")
	  REFERENCES "WEBPROJECT_DB"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_FREE
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD_FREE" ADD FOREIGN KEY ("ID")
	  REFERENCES "WEBPROJECT_DB"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_QNA
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD_QNA" ADD FOREIGN KEY ("ID")
	  REFERENCES "WEBPROJECT_DB"."MEMBER" ("ID") ENABLE;
